Repository menzStudy/CodingTestStudy, pull requests merged in 2023-05, with the labels that each got.

#1 01주차 - 신용호
  01주차/YongHo/_15649_.java
  01주차/YongHo/_1929_.java
  01주차/YongHo/_1978_.java
  01주차/YongHo/_4948_.java
  01주차/YongHo/_8393_.java
Labels: 100%

#2 01주차 - 신관호
  01주차/KwanHo/_15649_.java
  01주차/KwanHo/_1929_.java
  01주차/KwanHo/_1978_.java
  01주차/KwanHo/_4948_.java
  01주차/KwanHo/_8393_.java
  01주차/_4948_.java
Labels: 100% with answer

#3 01주차 - 이정석
  01주차/JeongSeok/_15649_.java
  01주차/JeongSeok/_1929_.java
  01주차/JeongSeok/_1978_.java
  01주차/JeongSeok/_4948_.java
  01주차/JeongSeok/_8393_.java
Labels: 100%

#4 2주차 화요일 - 신용호
  src/main/java/menz/study/week02/YongHo/_2609_.java
  src/main/java/menz/study/week02/YongHo/_9020_.java
Labels: 100%

#5 2주차 화요일 - 이정석
  src/main/java/menz/study/week02/JeongSeok/_2609_.java
  src/main/java/menz/study/week02/JeongSeok/_9020_.java
Labels: 100%

#6 2주차 화요일 - 신관호
  src/main/java/menz/study/week02/KwanHo/_2609_.java
  src/main/java/menz/study/week02/KwanHo/_9020_.java
Labels: 100%

#9 02주차 수요일 - 이정석
  src/main/java/menz/study/week02/JeongSeok/_11653_.java
  src/main/java/menz/study/week02/JeongSeok/_6588_.java
Labels: 100%

#10 2주차 목요일 - 이정석
  src/main/java/menz/study/week02/JeongSeok/_1182_.java
  src/main/java/menz/study/week02/JeongSeok/_6603_.java
Labels: 100% with answer

#13 2주차 목요일 - 신용호
  src/main/java/menz/study/week02/YongHo/_1182_.java
  src/main/java/menz/study/week02/YongHo/_6603_.java
Labels: 100% with answer

#14 2주차 금요일 - 신용호
  README.md
  src/main/java/menz/study/week02/YongHo/_15650_.java
  src/main/java/menz/study/week02/YongHo/_2981_.java
Labels: 100%

#16 2주차 금요일 - 이정석
  src/main/java/menz/study/week02/JeongSeok/_15650_.java
  src/main/java/menz/study/week02/JeongSeok/_2981_.java
  src/main/java/menz/study/week02/JeongSeok/_2981_memory.java
Labels: 100% with answer

#18 3주차 월요일 - 신관호
  src/main/java/menz/study/week03/KwanHo/_10974_.java
  src/main/java/menz/study/week03/KwanHo/_2407_.java
Labels: 100%

#17 3주차 월요일 - 이정석
  src/main/java/menz/study/week03/JeongSeok/_10974_.java
  src/main/java/menz/study/week03/JeongSeok/_2407_.java
  src/main/java/menz/study/week03/JeongSeok/_2407_failed.java
Labels: 100%

#19 3주차 월요일 - 신용호
  src/main/java/menz/study/week03/YongHo/_10974_.java
  src/main/java/menz/study/week03/YongHo/_2407_.java
Labels: 100%

#21 3주차 화요일 - 신용호
  src/main/java/menz/study/week03/YongHo/_17103_.java
  src/main/java/menz/study/week03/YongHo/_2824_.java
Labels: 100%

#20 3주차 화요일 - 신관호
  src/main/java/menz/study/week03/KwanHo/_17103_.java
  src/main/java/menz/study/week03/KwanHo/_2824_.java
Labels: 100%

#22 3주차 화요일 - 이정석
  src/main/java/menz/study/week03/JeongSeok/_17103_.java
  src/main/java/menz/study/week03/JeongSeok/_2824_.java
  src/main/java/menz/study/week03/JeongSeok/_2824_failed.java
Labels: 100%

#23 3주차 수요일 - 신용호
  src/main/java/menz/study/week03/YongHo/_10828_.java
  src/main/java/menz/study/week03/YongHo/_17087_.java
Labels: 100%

#24 3주차 수요일 - 신관호
  src/main/java/menz/study/week03/KwanHo/_10828_.java
  src/main/java/menz/study/week03/KwanHo/_17087_.java
Labels: 100%

#25 3주차 수요일 - 이정석
  src/main/java/menz/study/week03/JeongSeok/_10828_.java
  src/main/java/menz/study/week03/JeongSeok/_17087_.java
  src/main/java/menz/study/week03/JeongSeok/_17087_failed.java
Labels: 100%

#27 * feat: 9012반 - 괄호, 10773번 - 제로
  src/main/java/menz/study/week03/KwanHo/_10773_.java
  src/main/java/menz/study/week03/KwanHo/_9012_.java
Labels: 100%

#26 feat : 9012번 - 괄호 성공 코드 추가, 10773번 - 제로 성공 코드 추가
  src/main/java/menz/study/week03/JeongSeok/_10773_.java
  src/main/java/menz/study/week03/JeongSeok/_9012_.java
Labels: 100%

#29 3주차 금요일 - 신용호
  src/main/java/menz/study/week03/YongHo/_1406_.java
  src/main/java/menz/study/week03/YongHo/_1406_timeout.java
  src/main/java/menz/study/week03/YongHo/_1935_.java
Labels: 100%

#33 3주차 금요일 - 신관호
  src/main/java/menz/study/week03/KwanHo/_1406_.java
  src/main/java/menz/study/week03/KwanHo/_1935_.java
Labels: 100% with answer

#36 4주차 월요일 - 신용호
  src/main/java/menz/study/week04/YongHo/_10799_.java
  src/main/java/menz/study/week04/YongHo/_1874_.java
Labels: 100% with answer

#34 4주차 월요일 - 신관호
  src/main/java/menz/study/week04/_10799_.java
  src/main/java/menz/study/week04/_1874_.java
Labels: 100%

#35 4주차 월요일 - 이정석
  src/main/java/menz/study/week04/JeongSeok/_10799_.java
  src/main/java/menz/study/week04/JeongSeok/_1874_.java
Labels: 100% with answer

#43 4주차 수요일 - 이정석
  src/main/java/menz/study/week04/JeongSeok/_18258_.java
  src/main/java/menz/study/week04/JeongSeok/_2812_.java
  src/main/java/menz/study/week04/JeongSeok/_2812_failed_1.java
  src/main/java/menz/study/week04/JeongSeok/_2812_failed_2.java
Labels: 100%

#47 4주차 목요일 - 신용호
  src/main/java/menz/study/week04/YongHo/_10845_.java
  src/main/java/menz/study/week04/YongHo/_2164_.java
Labels: 100%

#46 4주차 목요일 - 이정석
  src/main/java/menz/study/week04/JeongSeok/_10845_.java
  src/main/java/menz/study/week04/JeongSeok/_2164_.java
Labels: 100%

#48 4주차 목요일 - 신관호
  src/main/java/menz/study/week04/KwanHo/_10845_.java
  src/main/java/menz/study/week04/KwanHo/_2164_.java
Labels: 100%

#53 5주차 월요일 - 신관호
  src/main/java/menz/study/week05/_11866_.java
  src/main/java/menz/study/week05/_1966_.java
Labels: 100% with answer

#54 5주차 월요일 - 이정석
  src/main/java/menz/study/week05/JeongSeok/_11866_.java
  src/main/java/menz/study/week05/JeongSeok/_1966_answer.java
Labels: 100% with answer

#52 5주차 월요일 - 신용호
  src/main/java/menz/study/week05/YongHo/_11866_.java
  src/main/java/menz/study/week05/YongHo/_1966_.java
Labels: 100%

#55 5주차 화요일 - 신용호
  src/main/java/menz/study/week05/YongHo/_11286_.java
  src/main/java/menz/study/week05/YongHo/_1927_.java
Labels: 100%

#56 5주차 화요일 - 이정석
  src/main/java/menz/study/week05/JeongSeok/_11286_.java
  src/main/java/menz/study/week05/JeongSeok/_1927_.java
Labels: 100%

#58 5주차 수요일 - 이정석
  src/main/java/menz/study/week05/JeongSeok/_1003_.java
  src/main/java/menz/study/week05/JeongSeok/_1003_memory.java
  src/main/java/menz/study/week05/JeongSeok/_5430_.java
  src/main/java/menz/study/week05/JeongSeok/_5430_failed.java
Labels: 100%

#59 5주차 수요일 - 신관호
  src/main/java/menz/study/week05/KwanHo/_1003_.java
  src/main/java/menz/study/week05/KwanHo/_1003_TimeOut.java
  src/main/java/menz/study/week05/KwanHo/_5430_.java
Labels: 100% with answer

#60 5주차 수요일 - 신용호
  src/main/java/menz/study/week05/YongHo/_1003_.java
  src/main/java/menz/study/week05/YongHo/_5430_.java
  src/main/java/menz/study/week05/YongHo/_5430_timeout.java
Labels: 100%

#62 5주차 목요일 - 신용호
  src/main/java/menz/study/week05/YongHo/_11726_.java
  src/main/java/menz/study/week05/YongHo/_9461_.java
Labels: 100%

#61 5주차 목요일 - 이정석
  src/main/java/menz/study/week05/JeongSeok/_11726_.java
  src/main/java/menz/study/week05/JeongSeok/_9461_.java
  src/main/java/menz/study/week05/JeongSeok/_9461_failed.java
Labels: 100%

#63 5주차 목요일 - 신관호
  src/main/java/menz/study/week05/KwanHo/_11726_.java
  src/main/java/menz/study/week05/KwanHo/_9461_.java
Labels: 100%

#66 5주차 금요일 - 신용호
  src/main/java/menz/study/week05/YongHo/_11727_.java
  src/main/java/menz/study/week05/YongHo/_9095_.java
Labels: 100%

#65 5주차 금요일 - 신관호
  src/main/java/menz/study/week05/KwanHo/_11727_.java
  src/main/java/menz/study/week05/KwanHo/_9095_.java
Labels: 100%

#64 5주차 금요일 - 이정석
  src/main/java/menz/study/week05/JeongSeok/_11727_.java
  src/main/java/menz/study/week05/JeongSeok/_9095_.java
Labels: 100%

#67 6주차 월요일 - 이정석
  src/main/java/menz/study/week06/JeongSeok/_15486_.java
  src/main/java/menz/study/week06/JeongSeok/_2193_.java
Labels: 100% with answer

#69 6주차 월요일 - 신관호
  src/main/java/menz/study/week06/KwanHo/_15486_.java
  src/main/java/menz/study/week06/KwanHo/_2193_.java
Labels: 100% with answer

#70 6주차 화요일 - 신관호
  src/main/java/menz/study/week06/KwanHo/_11053_.java
  src/main/java/menz/study/week06/KwanHo/_11722_.java
Labels: 100%

#68 6주차 화요일 - 이정석
  src/main/java/menz/study/week06/JeongSeok/_11053_.java
  src/main/java/menz/study/week06/JeongSeok/_11722_.java
Labels: 100%

#71 6주차 월요일 - 신용호
  src/main/java/menz/study/week06/YongHo/_15486_answer.java
  src/main/java/menz/study/week06/YongHo/_2193_.java
Labels: 60%

#72 6주차 화요일 - 신용호
  src/main/java/menz/study/week06/YongHo/_11053_.java
  src/main/java/menz/study/week06/YongHo/_11722_.java
Labels: 100%

#74 6주차 수요일 - 신관호
  src/main/java/menz/study/week06/KwanHo/_11055_.java
  src/main/java/menz/study/week06/KwanHo/_1912_.java
Labels: 100%

#75 6주차 수요일 - 신용호
  src/main/java/menz/study/week06/YongHo/_11055_.java
  src/main/java/menz/study/week06/YongHo/_1912_.java
Labels: 100%
